maintainer       "PHP app cookbook"
maintainer_email ""
license           "Apache 2.0"
description      "Installs/Configures phpapp"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"

name "vagrant_main"

depends	"mongodb"
depends "apache2"
depends "apt"
depends "build-essential"
depends "yum"
depends "chef_handler"
depends "mysql"
depends "networking_basic"
depends "openssl"
depends "php"
depends "php54"
depends "windows"
depends "xml"
depends "composer"
depends "phpmyadmin"